config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'tasks#index'

  resources :welcome

  resources :tasks do
    member do
      patch :change_completed
    end
    collection do
      get :completed
    end
  end

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  task_name   :string(255)
#  description :string(255)
#  status      :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

# require 'httparty'

class Task < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :importance
	geocoded_by :address
	reverse_geocoded_by :latitude, :longitude do |obj, results|
		if geo = results.first
			obj.street_number = geo.street_number
			obj.route = geo.route
			obj.state = geo.state
			obj.city = geo.city
			# obj.street_address = geo.street_address
			obj.zipcode = geo.postal_code
			obj.street_address = geo.street_address
		end
	end

	after_validation :geocode, :if => :address_changed?
	after_validation :reverse_geocode

	def set_bing_address_from_bing
		bing_data = get_bing_data
		address = bing_data["resourceSets"][0]["resources"][0]["address"]["formattedAddress"]
		self[:bing_address] = address
		self.save
	end

	def get_bing_data
		HTTParty.get('http://dev.virtualearth.net/REST/v1/Locations/@task.latitude.to_i,@task.longitude.to_i?key=Ah_f4EtXujIKRwM2DMfcrhaL_XJ0G_Ob_Yyy1nlDf0X_LYGhJilPBjWSfI91E3MV')
	end

	def location
		[latitude, longitude]
	end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  first_name             :string(255)
#  last_name              :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end

	def accout_update_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	# GET /tasks for current_user
	# GET new /task 
	def index
		if current_user
			@tasks = current_user.tasks.where(completed: false)
			@i1u0_tasks = @tasks.where(importance: 1, urgency: 0)
			@i1u1_tasks = @tasks.where(importance: 1, urgency: 1)
			@i0u0_tasks = @tasks.where(importance: 0, urgency: 0)
			@i0u1_tasks = @tasks.where(importance: 0, urgency: 1)
			@hash = geocode_tasks(@tasks)
		end
		@task = Task.new
		
	end

	def geocode_tasks(tasks)
		Gmaps4rails.build_markers(tasks) do |task, marker|
		  marker.lat task.latitude
		  marker.lng task.longitude
		  marker.infowindow "<a target='blank' href=#{task_path(task)}>#{task.task_name}: </a>"
		  marker.json({ title: task.task_name })
		end
	end

	def show
		@task = Task.find(params[:id])
		@tasks = Task.near(@task.location, 10) - [@task]

		if @task.geocoded?
			@nearby_tasks = Task.near(@task.location, 10).where(completed: false)
			@hash = geocode_tasks(@nearby_tasks)
		end

		@i1u0_tasks = @nearby_tasks.where(importance: 1, urgency: 0)
		@i1u1_tasks = @nearby_tasks.where(importance: 1, urgency: 1)
		@i0u0_tasks = @nearby_tasks.where(importance: 0, urgency: 0)
		@i0u1_tasks = @nearby_tasks.where(importance: 0, urgency: 1)
	end


	def completed
		@tasks = current_user.tasks.where(completed: true)
		@i1u0_tasks = @tasks.where(importance: 1, urgency: 0)
		@i1u1_tasks = @tasks.where(importance: 1, urgency: 1)
		@i0u0_tasks = @tasks.where(importance: 0, urgency: 0)
		@i0u1_tasks = @tasks.where(importance: 0, urgency: 1)
		@task = Task.new
		@hash = Gmaps4rails.build_markers(@tasks) do |task, marker|
		  marker.lat task.latitude
		  marker.lng task.longitude
		  marker.infowindow "<a target='blank' href=#{task_path(task)}>#{task.task_name}: </a>"
		  marker.json({ title: task.task_name })
		end
	end

	def new
		@task = Task.new
	end

	def edit
		@task = Task.find(params[:id])
	end

	def create
		new_task_params = task_params
		if new_task_params[:due_datetime] != ""
			new_task_params[:due_datetime] = DateTime.strptime(new_task_params[:due_datetime], '%m/%d/%Y %I:%M %p')
		end
		new_task_params[:importance] = task_params[:importance]
		new_task_params[:urgency] = task_params[:urgency]

		if current_user
			@task = current_user.tasks.build(new_task_params)
			if @task.save
				redirect_to tasks_path
			else
				redirect_to :back
			end
		else
			redirect_to new_user_session_path
		end

		
	end

	def update
		@task = Task.find(params[:id])
		if @task.update_attributes(task_params)
			redirect_to task_path(params[:id])
		else
			redirect_to :back
		end
	end

	def destroy
		@task = Task.find(params[:id])
		if @task.destroy
			redirect_to tasks_path
		else
			redirect_to :back
		end
	end

	def change_completed
		@task = Task.find(params[:id])
		if @task.completed
			val = false
		else
			val = true
		end
		@task.update_attributes(:completed => val)
		redirect_to tasks_path
	end

	def free_time
		@tasks = current_user.tasks.where(completed: false)
		@i1u0_tasks = @tasks.where(importance: 1, urgency: 0)
		@i1u1_tasks = @tasks.where(importance: 1, urgency: 1)
		@i0u0_tasks = @tasks.where(importance: 0, urgency: 0)
		@i0u1_tasks = @tasks.where(importance: 0, urgency: 1)
		@task = Task.new
		@hash = geocode_tasks(@tasks)
	end

	private

	def task_params
		params.require(:task).permit(:task_name, :est_time, :description, :status, :created_at, :updated_at, :due_datetime, :importance, :urgency, :latitude, :longitude, :address)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def format_date(date)
    if date
      date.strftime("%B %d, %Y")
    else
      "Date not specified"
    end
  end

  def format_time(time)
  	if time
  		time.strftime("%l:%M %p")
  	else
  		"Time not specified"
  	end
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
	def status_type
		[
			"Pending",
			"Completed",
			"Canceled"
		]
	end

	def travel_time(first_task, second_task)
		if first_task.street_address && second_task.street_address
      t_street_address = first_task.street_address.split("-").last
      a_street_address = second_task.street_address.split("-").last
    end

    if t_street_address && a_street_address
      response = HTTParty.get("http://dev.virtualearth.net/REST/V1/Routes?wp.0=#{format_string(t_street_address)}%20#{format_string(first_task.city)},#{format_string(first_task.state)}&wp.1=#{format_string(a_street_address)}%20#{format_string(second_task.city)},#{format_string(second_task.state)}&optmz=timeWithTraffic&key=Ah_f4EtXujIKRwM2DMfcrhaL_XJ0G_Ob_Yyy1nlDf0X_LYGhJilPBjWSfI91E3MV")
		end

    if response["resourceSets"][0]["resources"][0]["travelDurationTraffic"]
      "#{distance_of_time_in_words(response["resourceSets"][0]["resources"][0]["travelDurationTraffic"])} driving time"
    else 
    	"Travel Time Unavailable"
    end
  end

  def format_string(str)
  	str.gsub(' ','%20')
  end



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Goalgettr</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "application", "vendor/modernizr", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
  </head>

  <body>

  <div id="container">
    <div id="user_nav">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> |
        <%= link_to "Login", new_user_session_path %>
      <% end %>
    </div>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>

  </div>

    <%= yield %>
  </body>
</html>

app/views/tasks/_earlier_stuff.html.haml
.container
	= form_for @task do |f|
		= f.hidden_field :user_id, value: current_user.id
		.form-horizontal
			.fieldset
				.form-group
					.col-sm-2.control-label
						= f.label :task_name
					.col-sm-6
						= f.text_field :task_name, class: "form-control"
				.form-group
					.col-sm-2.control-label
						= f.label :description
					.col-sm-6
						= f.text_area :description, class: "form-control"
				.form-group
					.col-sm-2.control-label
						= f.label :due_datetime
					.col-sm-6
						.input-group
							.input-group-addon
								#datetimepicker1.glyphicon.glyphicon-calendar
								= f.text_field :due_datetime, class: "form-control"
				.form-group
					.col-sm-2.control-label
						= f.label :status
					.col-sm-6
						= f.select :status, status_type.each {|a| a.humanize}, class: "form-control"

				.actions
					.form-group
						.col-sm-6.col-sm-offset-2
							= f.submit 'Save', :class => "btn btn-primary form-control"
							= link_to 'Cancel', tasks_path, :class => "btn btn-default form-control"

app/views/tasks/_form.html.haml
.panel-body
	= form_for @task do |f|
		.form-group
			.col-xs-offset-5.col-xs-2.col-xs-offset-5
				= render 'quadrant_chooser'
				= f.hidden_field :importance
				= f.hidden_field :urgency
		.form-group
			.col-xs-6
				%br
				.input-group
					%span.input-group-addon
						.glyphicon.glyphicon-arrow-right
					= f.text_field :task_name, placeholder: 'Quick description', class: 'form-control'
			.col-xs-6
				%br
				.input-group
					%span.input-group-addon
						.glyphicon.glyphicon-time
					= f.text_field :est_time, placeholder: 'Est time', class: 'form-control'
		.form-group
			.col-xs-6
				.input-group
					%span.input-group-addon
						.glyphicon.glyphicon-map-marker
					= f.text_field :address, placeholder: 'Address', class: 'form-control'
			.col-xs-6
				.input-group
					%span.input-group-addon
						.glyphicon.glyphicon-calendar
					= f.text_field :due_datetime, placeholder: 'Due date and time', class: 'form-control'
		.form-group
			.col-xs-offset-2.col-xs-8.col-xs-offset-2
				%br
				%button.btn.btn-primary.btn-block
					Create

app/views/tasks/_map.html.erb
<script type="text/javascript">

handler = Gmaps.build('Google');
handler.buildMap({ 
provider: { maxZoom: 20 }, 
internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  

  if(navigator.geolocation)
    navigator.geolocation.getCurrentPosition(displayOnMap);
});

function displayOnMap(position){
  var geolocator = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude,
    name: 'Current location',
    infowindow: "<a target='blank' href='https://www.google.com/maps/place/"+position.coords.latitude+", "+position.coords.longitude+"'>Current location.</a>"
  });
  
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.map.centerOn(geolocator);
};
// handler = Gmaps.build('Google');
// handler.buildMap({
//     provider: {
//       disableDefaultUI: true
//       // pass in other Google Maps API options here
//     },
//     internal: {
//       id: 'map'
//     }
//   },
//   function(){
//     markers = handler.addMarkers([
//       {
//         "lat": 0,
//         "lng": 0,
//         "picture": {
//           "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
//           "width":  36,
//           "height": 36
//         },
//         "infowindow": "hello!"
//       }
//     ]);
//     handler.bounds.extendWith(markers);
//     handler.fitMapToBounds();
//   }
// );
</script>

app/views/tasks/_quadrant_chooser.html.haml
.quadrant_chooser
  .i1_u0
  .i1_u1
  .i0_u0
  .i0_u1

app/views/tasks/_task.html.haml
%li.task
	= t.task_name

app/views/tasks/_task_columns.html.haml
%li.task
	.row
		.col-xs-12.col-sm-2.normaler.col-md-2.normaler
			= link_to change_completed_task_path(t), method: :patch, class: "btn btn-default" do
				- unless t.completed == true
					%i.glyphicon.glyphicon-ok
				- else
					%i.glyphicon.glyphicon-arrow-left
		.col-xs-12.col-sm-6.text-center.col-md-7.active-icons
			- if t.est_time.to_i <= 30 || t.est_time == '10 min' || t.est_time == '30 min'
				%i.glyphicon.glyphicon-time.low{"data-placement" => "left", "data-toggle" => "tooltip", title: "Estimated time: #{t.est_time}", type: "button"}
			- elsif t.est_time.to_i <= 180 || t.est_time == '60 min' || t.est_time == '180 min' || t.est_time == '1 hr' || t.est_time == '3 hrs'
				%i.glyphicon.glyphicon-time.medium{"data-placement" => "left", "data-toggle" => "tooltip", title: "Estimated time: #{t.est_time}", type: "button"}
			- elsif t.est_time.to_i <= 300 || t.est_time == '300 min' || t.est_time == '5 hrs' || t.est_time == '3.5 hrs'
				%i.glyphicon.glyphicon-time.high{"data-placement" => "left", "data-toggle" => "tooltip", title: "Estimated time: #{t.est_time}", type: "button"}
			= t.task_name
			- if t.geocoded?
				= "(#{Task.near([t.latitude, t.longitude], 8).to_a.count- 1} nearby)"
		.col-xs-12.text-center.col-sm-4.col-md-3.active-icons.text-right
			= link_to task_path(t), method: :get do
				%i.glyphicon.glyphicon-info-sign{"data-placement" => "left", "data-toggle" => "tooltip", title: "Show details", type: "button"}
			= link_to edit_task_path(t), method: :get do
				%i.glyphicon.glyphicon-edit{"data-placement" => "left", "data-toggle" => "tooltip", title: "Edit task", type: "button"}
			= link_to t, method: :delete do
				%i.glyphicon.glyphicon-remove-circle{"data-placement" => "left", "data-toggle" => "tooltip", title: "Delete task", type: "button"}

app/views/tasks/_task_logic.html.haml
- if t.est_time == '10'
	%li.task
		= render 'task_columns', t: t
- elsif t.est_time == '30'
	%li.task
		= render 'task_columns', t: t
- elsif t.est_time == '60'
	%li.task
		= render 'task_columns', t: t
- elsif t.est_time == '180'
	%li.task
		= render 'task_columns', t: t
- elsif t.est_time == '300'
	%li.task
		= render 'task_columns', t: t
- else
	%li.task
		= render 'task_columns', t: t

app/views/tasks/_tcell.html.haml
%td= t.task_name
%td= t.description
%td= t.status
%td= format_date(t.due_datetime)
%td= format_time(t.due_datetime)
%td= button_to "View", task_path(t), method: "get", :class => "btn btn-xs btn-default"
%td= button_to "Edit", edit_task_path(t), method: :get, :class => "btn btn-xs btn-default"
%td= button_to "Delete", task_path(t), method: :delete, :class => "btn btn-xs btn-default"

app/views/tasks/_time_chooser.html.haml
.time_chooser
	.less_10
	.less_30
	.less_60
	.less_180
	.less_300

app/views/tasks/completed.html.haml
.container
	.row
		.col-lg-offset-5.col-lg-2
			%h3 Completed Tasks
	.row
		.col-lg-6#i1_u1_color
			%table.table
				.tbody#flowing
					%ul.list-unstyled
						- @i1u1_tasks.each do |t|
							= render 'task_columns', t: t
		.col-lg-6#i1_u0_color
			%table.table
				.tbody#flowing	
					%ul.list-unstyled
						- @i1u0_tasks.each do |t|
							= render 'task_columns', t: t
	.row
		.col-lg-6#i0_u1_color
			%table.table
				.tbody#flowing
					%ul.list-unstyled
						- @i0u1_tasks.each do |t|
							= render 'task_columns', t: t
		.col-lg-6#i0_u0_color
			%table.table
				.tbody#flowing	
					%ul.list-unstyled
						- @i0u0_tasks.each do |t|
							= render 'task_columns', t: t

app/views/tasks/edit.html.haml
.container
	.row
		.col-sm-6
			.panel.panel-primary
				.panel-heading
					%h3.panel-title
						Edit task
				.panel-body
					= form_for @task do |f|
						.form-group
							.col-md-offset-2.col-md-2.col-md-offset-2
								= render 'quadrant_chooser'
								= f.hidden_field :importance
								= f.hidden_field :urgency
							.col-md-6
								= f.select :status, status_type.each {|a| a.humanize}
						.form-group
							.col-md-offset-2.col-md-8.col-md-offset-2
								%br
								.input-group
									%span.input-group-addon
										.glyphicon.glyphicon-arrow-right
									= f.text_field :task_name, placeholder: 'Quick description', class: 'form-control'
						.form-group
							.col-md-offset-2.col-md-8.col-md-offset-2
								%br
								.input-group
									%span.input-group-addon
										.glyphicon.glyphicon-text-width
									= f.text_area :description, placeholder: 'Full description', class: 'form-control'
						.form-group
							.col-md-offset-2.col-md-8.col-md-offset-2
								%br
								.input-group
									%span.input-group-addon
										.glyphicon.glyphicon-time
									= f.text_field :est_time, placeholder: 'Est time', class: 'form-control'
						.form-group
							.col-md-offset-2.col-md-8.col-md-offset-2
								.input-group
									%span.input-group-addon
										.glyphicon.glyphicon-map-marker
									= f.text_field :address, placeholder: 'Address', class: 'form-control'
						.form-group
							.col-md-offset-2.col-md-8.col-md-offset-2
								.input-group
									%span.input-group-addon
										.glyphicon.glyphicon-calendar
									= f.text_field :due_datetime, placeholder: 'Due date and time', class: 'form-control'
						.form-group
							.col-md-offset-2.col-md-8.col-md-offset-2
								%br
								%button.btn.btn-warning.btn-block
									Edit

app/views/tasks/free_time.html.haml
/This is for (example) 30 minutes free time

app/views/tasks/index.html.haml
- content_for(:title, 'Your Tasks')
.container
	.row
		.col-sm-6
			.panel.panel-info
				.panel-heading
					%ul.nav.nav-pills{role: "tablist"}
						%li.active.panel-title
							%a{"data-toggle" => "pill", href: "#home", role: "tab"} Add a new task
						%li.panel-title
							%a{"data-toggle" => "pill", href: "#profile", role: "tab"} Find optimized tasks
				.tab-content
					#home.tab-pane.active 
						.panel-body
							= render 'form'
					#profile.tab-pane 
						.panel-body
							Free time task generation (enter your mindset/tags you would be okay with (either all or specify manually) and enter the amount of time you have available and the task or two you want to do for sure and it will use all this info + your location to figure out what tasks you can do). Free time attribute in users table for now.
							When you submit form:
							(hidden field)
							saves to current_user.current_location = ...
							(normal field to input)
							saves to current_user.free_time
							@tasks = Task.near(current_user.current_location, 10)
							@tasks.each do |task|
								if task.est_time <= current_user.free_time
									 link_to task.name, task_path(t)
									 (BE ABLE TO CLICK BOX LIKE IN FLAT UI AND SELECT TASKS THAT YOU WANT AND IT AUTOMATICALLY IMPORTS INTO ICLOUD CALENDAR
									 	(AlSO, BE ABLE TO CREATE CALENDAR IN ICLOUD CALENDAR THAT WHEN YOU ADD TASK OR SWITCH TASK TO THAT CALENDAR IT AUTOMATICALLY EXPORTS IT OUT AND IMPORTS IT INTO GOALGETTR, ie, TWO WAY IMPORT/EXPORT FOR BOTH))
		.col-sm-6
			.panel.panel-primary
				.panel-heading
					%h3.panel-title.text-center
						Task locations
				.panel-body
					/ %div
					/ 	#map{style: "width: 100%; height: 200px;"}
					/ 		= render "map"



	/ #i1_u0.quadrant
	/ 	%ol.sortable
	/ 		- @i1u0_tasks.each do |t|
	/ 			%li.task
	/ 				= t.task_name
	/ #i1_u1.quadrant
	/ 	%ol.sortable
	/ 		- @i1u1_tasks.each do |t|
	/ 			= render 'task', t: t
	/ #i0_u0.quadrant
	/ 	%ol.sortable
	/ 		- @i0u0_tasks.each do |t|
	/ 			= render 'task', t: t
	/ #i0_u1.quadrant
	/ 	.arrowhead
	/ 		%ol.sortable
	/ 			- @i0u1_tasks.each do |t|
	/ 				= render 'task', t: t


.container
	.row
		.col-lg-offset-5.col-lg-2
			%h3 Today
	.row
		.col-xs-6#i1_u1_color
			%table.table
				.tbody#flowing
					%ul.list-unstyled
						- if @i1u1_tasks
							- @i1u1_tasks.each do |t|
								= render 'task_columns', t: t
		.col-xs-6#i1_u0_color
			%table.table
				.tbody#flowing	
					%ul.list-unstyled
						- if @i1u0_tasks
							- @i1u0_tasks.each do |t|
								= render 'task_columns', t: t
	.row
		.col-xs-6#i0_u1_color
			%table.table
				.tbody#flowing
					%ul.list-unstyled
						- if @i0u1_tasks
							- @i0u1_tasks.each do |t|
								= render 'task_columns', t: t
		.col-xs-6#i0_u0_color
			%table.table
				.tbody#flowing	
					%ul.list-unstyled
						- if @i0u0_tasks
							- @i0u0_tasks.each do |t|
								= render 'task_columns', t: t

app/views/tasks/new.html.haml
new.html.haml